Repository internxt/website, pull requests merged in 2024-11, with the labels that each got.

#1145 [_]: hotfix/taiwanese translations
  src/assets/lang/zh-tw/priceCard.json
Labels: bug

#1147 [MKT-457]: Fix 10GB free plan banner to 1GB free plan
  src/assets/lang/ru/home.json
  src/assets/lang/ru/specialoffer/free-user.json
  src/assets/lang/zh/home.json
  src/assets/lang/zh/specialoffer/free-user.json
Labels: code review

#1148 [MKT-467]: Updating free plan banner text and price shown in price card
  src/assets/lang/de/banners.json
  src/assets/lang/en/banners.json
  src/assets/lang/es/banners.json
  src/assets/lang/fr/banners.json
  src/assets/lang/it/banners.json
  src/assets/lang/pt-br/banners.json
  src/assets/lang/ru/banners.json
  src/assets/lang/zh-tw/banners.json
  src/assets/lang/zh/banners.json
  src/components/shared/pricing/PriceCard.tsx
Labels: code review

#1150 [MKT-466]: fix/Security issue on temp mail
  package.json
  src/components/temp-email/HeroSection.tsx
  yarn.lock
Labels: enhancement

#1149 [_]: Update Internxt Drive Page
  src/components/shared/components/ProductsNavigation.tsx
  src/pages/drive.tsx
Labels: code review

#1151 [_]: feat/hiding FeaturesBanner in every page
  src/components/banners/FeaturesBanner.tsx
Labels: enhancement

#1153 [MKT_455]: feat/Adding business item to the navbar
  src/assets/lang/de/navbar.json
  src/assets/lang/en/navbar.json
  src/assets/lang/es/navbar.json
  src/assets/lang/fr/navbar.json
  src/assets/lang/it/navbar.json
  src/assets/lang/pt-br/navbar.json
  src/assets/lang/ru/navbar.json
  src/assets/lang/zh-tw/navbar.json
  src/assets/lang/zh/navbar.json
  src/assets/types/layout/navbar.ts
  src/components/layout/components/navbar/ItemsNavigation.tsx
Labels: enhancement

#1155 [_]: feat/ Hide banners
  src/pages/_app.tsx
Labels: enhancement

#1159 [_]: Update english FAQ answer
  src/assets/lang/en/black-friday.json
Labels: enhancement

#1163 [_]: feat/update CODEOWNERS
  .github/workflows/CODEOWNERS
Labels: enhancement
