Repository internxt/website, pull requests merged in 2024-06, with the labels that each got.

#858 [MKT-301]: feat/landing page for VPN
  cypress/e2e/components/redirect-button-component.cy.ts
  cypress/e2e/lifetime-page.cy.ts
  package.json
  public/images/vpn-extension/map.svg
  public/images/vpn-extension/superhero2.svg
  public/images/vpn-extension/vpn-extension.png
  public/images/vpn-extension/vpn-hero.svg
  public/images/vpn-extension/vpn-widget.svg
  src/assets/lang/de/banners.json
  src/assets/lang/de/components/tools/ToolSection.json
  src/assets/lang/de/footer.json
  src/assets/lang/en/banners.json
  src/assets/lang/en/components/tools/ToolSection.json
  src/assets/lang/en/footer.json
  src/assets/lang/en/metatags-descriptions.json
  src/assets/lang/en/vpn.json
  src/assets/lang/es/banners.json
  src/assets/lang/es/components/tools/ToolSection.json
  src/assets/lang/es/footer.json
  src/assets/lang/fr/banners.json
  src/assets/lang/fr/components/tools/ToolSection.json
  src/assets/lang/fr/footer.json
  src/assets/lang/it/banners.json
  src/assets/lang/it/components/tools/ToolSection.json
  src/assets/lang/it/footer.json
  src/assets/lang/ru/banners.json
  src/assets/lang/ru/components/tools/ToolSection.json
  src/assets/lang/ru/footer.json
  src/assets/lang/zh/banners.json
  src/assets/lang/zh/components/tools/ToolSection.json
  src/assets/lang/zh/footer.json
  src/components/banners/SignUpBanner.tsx
  src/components/banners/TopBanner.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Layout.tsx
  src/components/shared/HeroSectionSafeArea.tsx
  src/components/shared/RedirectButton.tsx
  src/components/shared/ToolsSection.tsx
  src/components/vpn-extension/EncryptedVPNSection.tsx
  src/components/vpn-extension/HeroSection.tsx
  src/components/vpn-extension/HowItWorksSection.tsx
  src/components/vpn-extension/SecureVPNSection.tsx
  src/components/vpn-extension/WhenUseVPNSection.tsx
  src/constants.ts
  src/pages/vpn.tsx
  yarn.lock
Labels: enhancement

#921 [_]: feat/snigel in all tools
  src/assets/lang/de/footer.json
  src/assets/lang/en/footer.json
  src/assets/lang/es/footer.json
  src/assets/lang/fr/footer.json
  src/assets/lang/it/footer.json
  src/assets/lang/ru/footer.json
  src/assets/lang/zh/footer.json
  src/components/converter-tool/ConversionTableSection.tsx
  src/components/converter-tool/ExplanationSection.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Layout.tsx
  src/components/password-generator/InfoSection.tsx
  src/pages/byte-converter.tsx
  src/pages/password-checker.tsx
  src/pages/password-generator.tsx
Labels: enhancement

#922 [_]: feat/snigel in file-converter
  src/components/file-converter/FeaturesSection.tsx
  src/components/file-converter/main-state/FeaturesSection.tsx
  src/components/layout/Layout.tsx
  src/components/layout/Navbar.tsx
Labels: enhancement

#923 [MKT-339]: feat/updating lifetime pages
  public/images/lifetime/file_item.webp
  src/assets/lang/de/navbar.json
  src/assets/lang/en/lifetime.json
  src/assets/lang/en/navbar.json
  src/assets/lang/es/navbar.json
  src/assets/lang/fr/navbar.json
  src/assets/lang/it/navbar.json
  src/assets/lang/ru/navbar.json
  src/assets/lang/zh/navbar.json
  src/components/layout/Navbar.tsx
  src/components/layout/components/navbar/ItemsNavigation.tsx
  src/components/lifetime/GetLifetimeSection.tsx
  src/components/lifetime/HeroSection.tsx
  src/components/lifetime/PriceTable.tsx
  src/components/prices/PriceCard.tsx
  src/pages/_app.tsx
  src/pages/lifetime/celebration.tsx
  src/pages/lifetime/index.tsx
  src/pages/lifetime_special.tsx
Labels: enhancement

#924 [_]: fix/remove webDav from product list
  src/assets/lang/de/navbar.json
  src/assets/lang/en/footer.json
  src/assets/lang/en/navbar.json
  src/assets/lang/es/footer.json
  src/assets/lang/es/navbar.json
  src/assets/lang/fr/footer.json
  src/assets/lang/fr/navbar.json
  src/assets/lang/it/footer.json
  src/assets/lang/it/navbar.json
  src/assets/lang/ru/footer.json
  src/assets/lang/ru/navbar.json
  src/assets/lang/zh/footer.json
  src/assets/lang/zh/navbar.json
  src/components/layout/Navbar.tsx
  src/components/layout/components/navbar/ItemsNavigation.tsx
Labels: enhancement

#928 [_]: fix/pc componentes prices
  src/components/services/stripe.service.ts
  src/pages/pccomponentes-products.tsx
Labels: bug

#929 [MKT-339]: feat/update stackcommerce and dealfuel pages
  cypress/e2e/lifetime-page.cy.ts
  package.json
  src/assets/lang/de/lifetime_special.json
  src/assets/lang/de/priceCard.json
  src/assets/lang/en/lifetime_special.json
  src/assets/lang/en/priceCard.json
  src/assets/lang/en/techcult.json
  src/assets/lang/es/lifetime_special.json
  src/assets/lang/es/priceCard.json
  src/assets/lang/es/privacy.json
  src/assets/lang/fr/lifetime_special.json
  src/assets/lang/fr/priceCard.json
  src/assets/lang/it/lifetime_special.json
  src/assets/lang/it/priceCard.json
  src/assets/lang/ru/lifetime_special.json
  src/assets/lang/ru/priceCard.json
  src/assets/lang/zh-tw/lifetime_special.json
  src/assets/lang/zh-tw/priceCard.json
  src/assets/lang/zh/lifetime_special.json
  src/assets/lang/zh/priceCard.json
  src/components/lifetime/HeroSection.tsx
  src/components/lifetime/PaymentSection.tsx
  src/components/lifetime/PriceTable.tsx
  src/components/prices/PriceCard.tsx
  src/components/services/stripe.service.ts
  src/pages/dealfuel.tsx
  src/pages/dealmirror.tsx
  src/pages/lifetime_special.tsx
  src/pages/mightydeals.tsx
  src/pages/privacy-directory.tsx
  src/pages/stackcommerce.tsx
  yarn.lock
Labels: enhancement

#927 [MKT-340]: feat/pCloud comparison
  public/logos/pcloud-alternative/inxt-logo-and-name.svg
  public/logos/pcloud-alternative/pCloud.svg
  public/logos/pcloud-alternative/pcloud-logo-and-name.svg
  src/assets/lang/en/banners.json
  src/assets/lang/en/metatags-descriptions.json
  src/assets/lang/en/pcloud-alternative.json
  src/components/banners/SignUpBanner.tsx
  src/components/comparison/ComparisonHeader.tsx
  src/components/comparison/TableSection.tsx
  src/components/comparison/pCloud-alternative/HeroSection.tsx
  src/components/comparison/pCloud-alternative/IsPCloudSafeSection.tsx
  src/components/comparison/pCloud-alternative/TablesSection.tsx
  src/components/comparison/pCloud-alternative/WhyChooseInxtSection.tsx
  src/components/layout/MinimalFooter.tsx
  src/pages/cloud-storage-comparison.tsx
  src/pages/lifetime/celebration.tsx
  src/pages/lifetime/index.tsx
  src/pages/lifetime_special.tsx
  src/pages/pcloud-alternative.tsx
Labels: enhancement

#931 [_]: feat/pcloud design
  src/assets/lang/en/pcloud-alternative.json
  src/components/comparison/ComparisonHeader.tsx
  src/components/comparison/pCloud-alternative/CouponSection.tsx
  src/components/comparison/pCloud-alternative/TablesSection.tsx
  src/components/comparison/pCloud-alternative/components/CompetitorTable.tsx
  src/pages/pcloud-alternative.tsx
Labels: enhancement

#932 [MKT-342]: feat/banners for soft sale
  src/assets/lang/de/banners.json
  src/assets/lang/en/banners.json
  src/assets/lang/es/banners.json
  src/assets/lang/fr/banners.json
  src/assets/lang/it/banners.json
  src/assets/lang/ru/banners.json
  src/assets/lang/zh-tw/banners.json
  src/assets/lang/zh/banners.json
  src/components/banners/TopBanner.tsx
  src/components/components/Countdown.tsx
  src/components/layout/Layout.tsx
  src/components/layout/Navbar.tsx
  src/components/lifetime/HeroSection.tsx
  src/constants.ts
  src/pages/_app.tsx
  src/pages/dealfuel.tsx
  src/pages/dealmirror.tsx
  src/pages/lifetime/index.tsx
  src/pages/stackcommerce.tsx
Labels: enhancement

#940 [_]: feat/remove lifetime banner
  src/pages/_app.tsx
Labels: enhancement

#942 [MKT-329]: feat/price table to home page
  src/assets/lang/de/home.json
  src/assets/lang/de/priceCard.json
  src/assets/lang/en/home.json
  src/assets/lang/en/priceCard.json
  src/assets/lang/es/home.json
  src/assets/lang/es/priceCard.json
  src/assets/lang/fr/home.json
  src/assets/lang/fr/priceCard.json
  src/assets/lang/it/home.json
  src/assets/lang/it/priceCard.json
  src/assets/lang/ru/home.json
  src/assets/lang/ru/priceCard.json
  src/assets/lang/zh-tw/home.json
  src/assets/lang/zh-tw/priceCard.json
  src/assets/lang/zh/home.json
  src/assets/lang/zh/priceCard.json
  src/components/prices/PriceTable.tsx
  src/pages/index.tsx
Labels: enhancement

#943 [_]: feat/update free plan space
  src/assets/lang/de/banners.json
  src/assets/lang/de/cloud-storage-for-education.json
  src/assets/lang/de/comparison.json
  src/assets/lang/de/home.json
  src/assets/lang/de/metatags-descriptions.json
  src/assets/lang/de/password-checker.json
  src/assets/lang/de/priceCard.json
  src/assets/lang/de/pricing.json
  src/assets/lang/en/banners.json
  src/assets/lang/en/child-safety-ebook.json
  src/assets/lang/en/cloud-storage-for-education.json
  src/assets/lang/en/comparison.json
  src/assets/lang/en/home.json
  src/assets/lang/en/metatags-descriptions.json
  src/assets/lang/en/newsletter.json
  src/assets/lang/en/online-privacy-ebook.json
  src/assets/lang/en/password-checker.json
  src/assets/lang/en/priceCard.json
  src/assets/lang/en/pricing.json
  src/assets/lang/es/cloud-storage-for-education.json
  src/assets/lang/es/comparison.json
  src/assets/lang/es/file-converter/file-converter.json
  src/assets/lang/es/home.json
  src/assets/lang/es/metatags-descriptions.json
  src/assets/lang/es/password-checker.json
  src/assets/lang/es/priceCard.json
  src/assets/lang/es/pricing.json
  src/assets/lang/fr/cloud-storage-for-education.json
  src/assets/lang/fr/comparison.json
  src/assets/lang/fr/home.json
  src/assets/lang/fr/password-checker.json
  src/assets/lang/fr/priceCard.json
  src/assets/lang/fr/pricing.json
  src/assets/lang/it/banners.json
  src/assets/lang/it/cloud-storage-for-education.json
  src/assets/lang/it/comparison.json
  src/assets/lang/it/home.json
  src/assets/lang/it/metatags-descriptions.json
  src/assets/lang/it/password-checker.json
  src/assets/lang/it/priceCard.json
  src/assets/lang/it/pricing.json
  src/assets/lang/ru/cloud-storage-for-education.json
  src/assets/lang/zh-tw/banners.json
  src/assets/lang/zh-tw/child-safety-ebook.json
  src/assets/lang/zh-tw/cloud-storage-for-education.json
  src/assets/lang/zh-tw/comparison.json
  src/assets/lang/zh-tw/home.json
  src/assets/lang/zh-tw/newsletter.json
  src/assets/lang/zh-tw/online-privacy-ebook.json
  src/assets/lang/zh-tw/priceCard.json
  src/assets/lang/zh-tw/pricing.json
  src/assets/lang/zh/banners.json
  src/assets/lang/zh/cloud-storage-for-education.json
  src/assets/lang/zh/home.json
  src/assets/lang/zh/metatags-descriptions.json
  src/assets/lang/zh/password-checker.json
  src/components/banners/LoginBFBanner.tsx
  src/components/comparison/TableSection.tsx
Labels: enhancement

#946 [_]: fix/spanish page seo
  cypress/e2e/pricing/lifetime-products.cy.ts
  cypress/e2e/pricing/monthly-products.cy.ts
  cypress/e2e/pricing/yearly-products.cy.ts
  cypress/support/commands.ts
  src/assets/lang/de/footer.json
  src/assets/lang/es/footer.json
  src/assets/lang/es/metatags-descriptions.json
  src/assets/lang/fr/footer.json
  src/assets/lang/it/footer.json
  src/assets/lang/ru/footer.json
  src/assets/lang/zh/footer.json
  src/components/inxt-library/main/HeroSection.tsx
  src/components/layout/Footer.tsx
  src/pages/sitemap.xml.js
Labels: enhancement

#947 [_]: feat/serve-assets-from-cdn
  .env.local.example
  next.config.js
  src/components/about/HeroSection.tsx
Labels: enhancement

#952 [_]: feat/home page v2
  src/assets/lang/de/home.json
  src/assets/lang/de/navbar.json
  src/assets/lang/en/home.json
  src/assets/lang/en/navbar.json
  src/assets/lang/es/home.json
  src/assets/lang/es/navbar.json
  src/assets/lang/fr/home.json
  src/assets/lang/fr/navbar.json
  src/assets/lang/it/home.json
  src/assets/lang/it/navbar.json
  src/assets/lang/ru/home.json
  src/assets/lang/ru/navbar.json
  src/assets/lang/zh-tw/home.json
  src/assets/lang/zh-tw/navbar.json
  src/assets/lang/zh/home.json
  src/assets/lang/zh/navbar.json
  src/components/about/CompanySection.tsx
  src/components/home/ChooseStorageSizeSection.tsx
  src/components/home/FeatureSectionV2.tsx
  src/components/home/HeroSection.tsx
  src/components/home/TestimonialsSection.tsx
  src/components/home/components/heroSection/TitleAndSignup.tsx
  src/components/home/components/heroSection/TitleAndSurvey.tsx
  src/components/layout/Layout.tsx
  src/components/layout/Navbar.tsx
  src/components/shared/CtaSection.tsx
  src/components/shared/StarsRate.tsx
  src/components/specialoffer/MarqueeComponent.tsx
  src/pages/annual.tsx
  src/pages/cyber-awareness.tsx
  src/pages/drive.tsx
  src/pages/index.tsx
  src/pages/media-area.tsx
  src/pages/partner-discount.tsx
Labels: enhancement

#948 [MKT-382]: feat/update home page
  src/assets/lang/de/home.json
  src/assets/lang/de/navbar.json
  src/assets/lang/en/home.json
  src/assets/lang/en/navbar.json
  src/assets/lang/es/home.json
  src/assets/lang/es/navbar.json
  src/assets/lang/fr/home.json
  src/assets/lang/fr/navbar.json
  src/assets/lang/it/home.json
  src/assets/lang/it/navbar.json
  src/assets/lang/ru/home.json
  src/assets/lang/ru/navbar.json
  src/assets/lang/zh-tw/home.json
  src/assets/lang/zh-tw/navbar.json
  src/assets/lang/zh/home.json
  src/assets/lang/zh/navbar.json
  src/components/about/CompanySection.tsx
  src/components/home/ChooseStorageSizeSection.tsx
  src/components/home/FeatureSectionV2.tsx
  src/components/home/FirstFeaturesSection.tsx
  src/components/home/FirstWhatWeDoSection.tsx
  src/components/home/HeroSection.tsx
  src/components/home/SecondFeaturesSection.tsx
  src/components/home/SecondWhatWeDoSection.tsx
  src/components/home/SocialProofSection.tsx
  src/components/home/TestimonialsSection.tsx
  src/components/home/components/Animation.tsx
  src/components/home/components/Label.tsx
  src/components/home/components/heroSection/TitleAndSignup.tsx
  src/components/home/components/heroSection/TitleAndSurvey.tsx
  src/components/layout/Layout.tsx
  src/components/layout/Navbar.tsx
  src/components/layout/components/LanguageBox.tsx
  src/components/layout/components/navbar/ItemsNavigation.tsx
  src/components/prices/PriceTable.tsx
  src/components/shared/CtaSection.tsx
  src/components/shared/FaqSection.tsx
  src/components/shared/Header.tsx
  src/components/shared/ProductCard.tsx
  src/components/shared/StarsRate.tsx
  src/components/specialoffer/MarqueeComponent.tsx
  src/pages/_app.tsx
  src/pages/annual.tsx
  src/pages/cyber-awareness.tsx
  src/pages/drive.tsx
  src/pages/index.tsx
  src/pages/media-area.tsx
  src/pages/partner-discount.tsx
Labels: enhancement

#953 [_]: feat/add home page variation
  src/pages/b.tsx
  src/pages/index.tsx
Labels: enhancement

#954 [MKT-372]: feat/before you go banner
  src/assets/lang/de/banners.json
  src/assets/lang/en/banners.json
  src/assets/lang/es/banners.json
  src/assets/lang/fr/banners.json
  src/assets/lang/it/banners.json
  src/assets/lang/ru/banners.json
  src/assets/lang/zh-tw/banners.json
  src/assets/lang/zh/banners.json
  src/components/banners/BeforeCloseTabBanner.tsx
  src/components/banners/FreeCardPromoBanner.tsx
  src/components/home/SocialProofSection.tsx
  src/contexts/GlobalUIManager/GlobalUIManager.context.tsx
  src/pages/_app.tsx
Labels: enhancement

#956 [_]: fix/build
  src/components/shared/Button.tsx
Labels: enhancement

#951 [MKT-346]: feat/template for Independence Day
  .gitignore
  cypress/e2e/auth.cy.ts
  cypress/e2e/lifetime-page.cy.ts
  cypress/e2e/pricing/lifetime-products.cy.ts
  cypress/e2e/pricing/monthly-products.cy.ts
  cypress/e2e/pricing/yearly-products.cy.ts
  src/assets/lang/en/lifetime.json
  src/assets/lang/fr/lifetime.json
  src/components/lifetime/FeatureSection.tsx
  src/components/lifetime/HeroSection.tsx
  src/constants.ts
  src/pages/_app.tsx
  src/pages/lifetime/celebration/[filename].tsx
Labels: enhancement

#958 [MKT-384]: test/fix tests
  cypress.config.ts
  cypress/e2e/auth.cy.ts
  cypress/e2e/lifetime-page.cy.ts
  cypress/e2e/pricing/lifetime-products.cy.ts
  cypress/e2e/pricing/monthly-products.cy.ts
  cypress/e2e/pricing/yearly-products.cy.ts
  cypress/support/commands.ts
  package.json
  src/components/prices/PriceTable.tsx
  yarn.lock
Labels: bug, dependencies
