Repository internxt/website, pull requests merged in 2024-10, with the labels that each got.

#1075 [MKT-451]: feat/cyber awareness campaign
  src/assets/lang/de/banners.json
  src/assets/lang/de/home.json
  src/assets/lang/de/pricing.json
  src/assets/lang/en/banners.json
  src/assets/lang/en/home.json
  src/assets/lang/en/pricing.json
  src/assets/lang/es/banners.json
  src/assets/lang/es/home.json
  src/assets/lang/es/pricing.json
  src/assets/lang/fr/banners.json
  src/assets/lang/fr/home.json
  src/assets/lang/fr/pricing.json
  src/assets/lang/it/banners.json
  src/assets/lang/it/home.json
  src/assets/lang/it/pricing.json
  src/assets/lang/pt-br/banners.json
  src/assets/lang/pt-br/home.json
  src/assets/lang/ru/banners.json
  src/assets/lang/ru/home.json
  src/assets/lang/ru/pricing.json
  src/assets/lang/zh-tw/banners.json
  src/assets/lang/zh-tw/home.json
  src/assets/lang/zh-tw/pricing.json
  src/assets/lang/zh/banners.json
  src/assets/lang/zh/home.json
  src/assets/lang/zh/lifetime.json
  src/assets/lang/zh/pricing.json
  src/components/banners/BottomBanner.tsx
  src/components/banners/HomePageBannerForMobile.tsx
  src/components/banners/S3Banner.tsx
  src/components/banners/TopBanner.tsx
  src/components/cyber-awareness/HeroSection.tsx
  src/components/home/HeroSection.tsx
  src/components/lifetime/PriceBannerForCampaigns.tsx
  src/components/services/stripe.service.ts
  src/components/shared/pricing/PricingSection.tsx
  src/components/shared/pricing/PricingSectionWrapper.tsx
  src/components/shared/pricing/components/PlanSelector.tsx
  src/lib/auth.ts
  src/lib/types/index.ts
  src/pages/_app.tsx
  src/pages/business.tsx
  src/pages/cyber-awareness.tsx
  src/pages/family.tsx
  src/pages/index.tsx
  src/pages/locker.tsx
  src/pages/pccomponentes-products-b2b.tsx
  src/pages/pricing/index.tsx
Labels: enhancement

#1104 [_]: fix/taiwan currency and visual percentage error
  src/assets/lang/zh-tw/lifetime.json
  src/pages/lifetime/celebration/[filename].tsx
Labels: code review

#1106 [_]: feat/Features banner
  src/assets/lang/de/banners.json
  src/assets/lang/en/banners.json
  src/assets/lang/es/banners.json
  src/assets/lang/fr/banners.json
  src/assets/lang/it/banners.json
  src/assets/lang/pt-br/banners.json
  src/assets/lang/ru/banners.json
  src/assets/lang/zh-tw/banners.json
  src/assets/lang/zh/banners.json
  src/components/banners/FeaturesBanner.tsx
  src/pages/_app.tsx
Labels: enhancement

#1107 [_]: fix/interval plan selector
  src/components/shared/pricing/PricingSection.tsx
  src/components/shared/pricing/PricingSectionWrapper.tsx
  src/components/shared/pricing/components/PlanSelector.tsx
Labels: bug

#1108 [_]: fix/features banner width for mobile
  src/components/banners/FeaturesBanner.tsx
Labels: bug

#1110 [MKT-460]: feat/Resurrection Campaing LP
  src/assets/lang/en/comeback.json
  src/assets/lang/en/metatags-descriptions.json
  src/assets/types/resurrection.ts
  src/components/lifetime/HeroSection.tsx
  src/components/shared/CtaSection.tsx
  src/components/shared/pricing/PricingSection.tsx
  src/components/shared/pricing/PricingSectionWrapper.tsx
  src/components/shared/pricing/components/PlanSelector.tsx
  src/constants.ts
  src/lib/types/index.ts
  src/pages/comeback.tsx
Labels: code review

#1113 [_]:Fixing some Ctas Redirection
  src/pages/lifetime/index.tsx
  src/pages/stackcommerce.tsx
Labels: code review

#1115 [_]: feat/delete dealmirror LP
  src/pages/dealmirror.tsx
Labels: code review

#1116 Update Footer.tsx
  src/components/layout/footers/Footer.tsx
Labels: code review

#1114 [MKT-462]: feat/Halloween LP
  src/assets/lang/de/banners.json
  src/assets/lang/de/home.json
  src/assets/lang/de/metatags-descriptions.json
  src/assets/lang/de/priceCard.json
  src/assets/lang/de/pricing.json
  src/assets/lang/en/banners.json
  src/assets/lang/en/home.json
  src/assets/lang/en/metatags-descriptions.json
  src/assets/lang/en/priceCard.json
  src/assets/lang/en/pricing.json
  src/assets/lang/es/banners.json
  src/assets/lang/es/home.json
  src/assets/lang/es/metatags-descriptions.json
  src/assets/lang/es/priceCard.json
  src/assets/lang/es/pricing.json
  src/assets/lang/fr/banners.json
  src/assets/lang/fr/home.json
  src/assets/lang/fr/metatags-descriptions.json
  src/assets/lang/fr/priceCard.json
  src/assets/lang/fr/pricing.json
  src/assets/lang/it/banners.json
  src/assets/lang/it/home.json
  src/assets/lang/it/metatags-descriptions.json
  src/assets/lang/it/priceCard.json
  src/assets/lang/it/pricing.json
  src/assets/lang/pt-br/banners.json
  src/assets/lang/pt-br/home.json
  src/assets/lang/pt-br/metatags-descriptions.json
  src/assets/lang/pt-br/priceCard.json
  src/assets/lang/ru/banners.json
  src/assets/lang/ru/home.json
  src/assets/lang/ru/metatags-descriptions.json
  src/assets/lang/ru/priceCard.json
  src/assets/lang/ru/pricing.json
  src/assets/lang/zh-tw/banners.json
  src/assets/lang/zh-tw/home.json
  src/assets/lang/zh-tw/metatags-descriptions.json
  src/assets/lang/zh-tw/pricing.json
  src/assets/lang/zh/banners.json
  src/assets/lang/zh/home.json
  src/assets/lang/zh/metatags-descriptions.json
  src/assets/lang/zh/priceCard.json
  src/assets/lang/zh/pricing.json
  src/assets/types/pricing.ts
  src/components/banners/BottomBanner.tsx
  src/components/banners/FeaturesBanner.tsx
  src/components/banners/HomePageBannerForMobile.tsx
  src/components/banners/TopBanner.tsx
  src/components/home/HeroSection.tsx
  src/components/lifetime/PriceBannerForCampaigns.tsx
  src/components/shared/pricing/PriceCard.tsx
  src/components/shared/pricing/PricingSection.tsx
  src/components/shared/pricing/PricingSectionWrapper.tsx
  src/components/shared/pricing/components/PlanSelector.tsx
  src/hooks/usePlanSelection.ts
  src/lib/types/index.ts
  src/pages/index.tsx
  src/pages/locker.tsx
  src/pages/partner-discount.tsx
  src/pages/pricing/index.tsx
Labels: enhancement

#1117 Update Footer.tsx
  src/components/layout/footers/Footer.tsx
Labels: enhancement, code review

#1119 [_]: fix/banner text and price cards
  src/assets/lang/de/banners.json
  src/assets/lang/de/pricing.json
  src/assets/lang/en/banners.json
  src/assets/lang/en/pricing.json
  src/assets/lang/es/banners.json
  src/assets/lang/es/pricing.json
  src/assets/lang/fr/banners.json
  src/assets/lang/fr/pricing.json
  src/assets/lang/it/banners.json
  src/assets/lang/it/pricing.json
  src/assets/lang/ru/banners.json
  src/assets/lang/ru/pricing.json
  src/assets/lang/zh-tw/banners.json
  src/assets/lang/zh-tw/pricing.json
  src/assets/lang/zh/banners.json
  src/assets/lang/zh/pricing.json
  src/components/shared/pricing/PriceCard.tsx
Labels: bug

#1120 [MKT-458]: feat/preBlackFridayLP
  src/assets/lang/de/black-friday.json
  src/assets/lang/en/black-friday.json
  src/assets/lang/es/black-friday.json
  src/assets/lang/fr/black-friday.json
  src/assets/lang/it/black-friday.json
  src/assets/lang/ru/black-friday.json
  src/assets/lang/zh-tw/black-friday.json
  src/assets/lang/zh/black-friday.json
  src/components/black-friday/BF-HeroSection.module.scss
  src/components/black-friday/BestStorageSection.tsx
  src/components/black-friday/CtaSection.tsx
  src/components/black-friday/FAQSection.tsx
  src/components/black-friday/FeatureSection.tsx
  src/components/black-friday/HeroSection.tsx
  src/components/black-friday/PlatformSection.tsx
  src/components/black-friday/SuiteSection.tsx
  src/components/black-friday/TestimonialsSection.tsx
  src/components/black-friday/components/ButtonDeal.tsx
  src/components/home/TestimonialsSection.tsx
  src/components/layout/Layout.tsx
  src/components/layout/components/LanguageBox.tsx
  src/components/layout/footers/MinimalFooter.tsx
  src/components/layout/navbars/Navbar.tsx
  src/components/shared/CardGroup.tsx
  src/components/shared/Header.tsx
  src/components/shared/components/PlatformSection.tsx
  src/components/shared/components/TextAndCardsGroupColumnSection.tsx
  src/constants.ts
  src/pages/black-friday.tsx
  tailwind.config.js
Labels: enhancement

#1123 [_]: fix/Startpage prices
  src/components/annual-plans-for-affiliates/components/PriceTable.tsx
Labels: bug

#1105 [MKT-459]: feat/Singles Day LP
  src/assets/lang/en/metatags-descriptions.json
  src/assets/lang/en/singles-day.json
  src/assets/lang/zh-tw/metatags-descriptions.json
  src/assets/lang/zh-tw/singles-day.json
  src/assets/lang/zh/metatags-descriptions.json
  src/assets/lang/zh/singles-day.json
  src/assets/types/singles-day.ts
  src/components/layout/components/LanguageBox.tsx
  src/components/layout/components/LanguageMobileBox.tsx
  src/components/layout/navbars/Navbar.tsx
  src/components/lifetime/FeatureSection.tsx
  src/components/lifetime/PaymentSection.tsx
  src/components/lifetime/PriceTable.tsx
  src/components/shared/components/HeroSection.tsx
  src/components/shared/components/PlatformSection.tsx
  src/constants.ts
  src/lib/types/index.ts
  src/pages/comeback.tsx
  src/pages/lifetime/celebration/singlesday.tsx
Labels: enhancement

#1127 [MKT-469]: feat/electionsLP
  src/assets/lang/en/elections.json
  src/assets/lang/en/metatags-descriptions.json
  src/assets/types/elections.ts
  src/components/components/Countdown.tsx
  src/components/elections/PlanSelector.tsx
  src/components/home/components/Animation.tsx
  src/components/lifetime/HeroSection.tsx
  src/components/lifetime/PaymentSection.tsx
  src/components/lifetime/PriceTable.tsx
  src/components/prices/PriceCard.tsx
  src/constants.ts
  src/hooks/usePricing.ts
  src/lib/types/index.ts
  src/pages/elections.tsx
Labels: enhancement

#1132 [_]: fix/initial coupon code
  src/components/lifetime/PaymentSection.tsx
  src/pages/elections.tsx
Labels: bug
